import {
  AlertCircle,
  AlertTriangle,
  Bell,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CheckCircle2,
  Clock3,
  DoorOpen,
  Eye,
  FileBarChart2,
  FileSpreadsheet,
  Gift,
  HandCoins,
  HeartHandshake,
  Hourglass,
  Inbox,
  List,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Package,
  Play,
  Printer,
  Search,
  Send,
  ShieldAlert,
  User,
  UserCheck,
  Users,
  Wallet,
  XCircle,
} from 'lucide-react';

const ICONS = {
  dashboard: CalendarDays,
  events: Calendar,
  announcements: Megaphone,
  appointments: CalendarClock,
  attendance: CalendarCheck,
  donations: Gift,
  reports: FileBarChart2,
  users: Users,
  logout: DoorOpen,
  search: Search,
  empty: Inbox,
  expired: Clock3,
  pending: Hourglass,
  approved: CheckCircle2,
  rejected: XCircle,
  cancelled: ShieldAlert,
  completed: CheckCircle2,
  greeting: HandCoins,
  upcoming: CalendarClock,
  ongoing: Play,
  attendees: Users,
  cash: Wallet,
  donation: HeartHandshake,
  list: List,
  calendar: CalendarDays,
  location: MapPin,
  organizer: User,
  alert: AlertTriangle,
  mail: Mail,
  lock: Lock,
  profile: User,
  info: AlertCircle,
  print: Printer,
  food: Send,
  supplies: Package,
  money: HandCoins,
  status: Eye,
  create: Calendar,
  publish: Bell,
  file: FileSpreadsheet,
  review: UserCheck,
};

export default function AppIcon({ name, size = 16, className = '', strokeWidth = 2 }) {
  const Icon = ICONS[name] || AlertCircle;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}
